        XTEXT HDOS
        ORG   USERFWA


***     DEMO3.ASM-CONSOLE INPUT DEMO,
*       IN CHARACTER MODE
*
*       THIS IS A SIMPLE DEMONSTRATION PROGRAM
*       THAT INPUTS CHARACTERS FROM THE CONSOLE,
*       AND TYPES THEM BACK AGAIN.
*
*       IF THE LAST CHARACTER YOU ENTERED CONTAINED A
*       ('.') THEN DEMO3 EXITS TO HDOS AFTER
*       TYPING THE LINE.


***     TO RUN THIS PROGRAM, TYPE THE FOLLOWING:
*       (DO NOT TYPE COMMENTS IN PARENTHESIS)
*
*       >RUN ASM
*       *DEMO3,TT:=DEMO3  (WRITES LISTING
*                          TO CONSOLE)
*       >RUN DEMO3
*       HI, I'M DEMO3!    (DEMO3 TYPES THIS)
*       AABBCCDD          (YOU TYPE ABCD, DEMO3 ECHOS IT)
*       XXYY..            (YOU TYPE 'XY.', DEMO3 ECHOS IT)
*       >                 (DEMO3 EXITS TO HDOS)
ENTRY  LXI      H,DEMOA    EXECUTION STARTS HERE
       SCALL    .PRINT     PRINT 'HI!' MESSAGE

*      SETUP CHARACTER MODE. SINCE HDOS WILL ECHO
*      THE CHARACTERS, AND THEN DEMO3 WILL TYPE
*      THEM, CHARACTERS WILL BE DOUBLED ON THE
*      SCREEN AS THEY ARE TYPED.

       XRA     A
       MVI     B,0001Q    CHARACTER MODE WITH ECHO
       MVI     C,201Q
       SCALL   .CONSL

*      LOOP ECHOING LINES

ECHO   SCALL   .SCIN
       JC      ECHO       NO CHARACTER YET
       CPI     '.'
       JNE     ECHO1      NOT PERIOD CHARACTER
       STA     ENDFLAG    MAKE ENDFLAG NON-ZERO
                          (A '.', IN FACT)
ECHO1  SCALL   .SCOUT     TYPE CHARACTER BACK
       LDA     ENDFLAG
       ANA     A
       JZ      ECHO       STILL MORE TO GO
*      I HAVE SEEN '.', WILL RETURN TO HDOS

       XRA     A
       SCALL   .EXIT      RETURN TO HDOS

DEMOA  DD      12Q,'HI, I'M DEMO3!',212Q
ENDFLAG DB     0          <>0 IF TO EXIT

       END     ENTRY
