        XTEXT HDOS
        ORG   USERFWA


***     DEMO2.ASM-CONSOLE INPUT DEMO, IN LINE MODE
*
*       THIS IS A SIMPLE DEMONSTRATION PROGRAM
*       THAT INPUTS LINES FROM THE CONSOLE,
*       AND TYPES THEM BACK AGAIN.
*
*       IF THE LAST LINE YOU ENTERED CONTAINED A
*       ('.') THEN DEMO2 EXITS TO HDOS AFTER
*       TYPING THE LINE.


***     TO RUN THIS PROGRAM, TYPE THE FOLLOWING:
*       (DO NOT TYPE COMMENTS IN PARENTHESIS)
*
*       >RUN ASM
*       *DEMO2,TT:=DEMO2  (WRITES LISTING
*                          TO CONSOLE)
*       >RUN DEMO2
*       HI, I'M DEMO2!    (DEMO2 TYPES THIS)
*       ABCD              (YOU TYPE THIS)
*       ABCD              (DEMO2 TYPES THIS)
*       IS ANYONE THERE?  (YOU TYPE THIS)
*       IS ANYONE THERE?  (DEMO2 TYPES THIS)
*       BYE BYE.          (YOU TYPE THIS)
*       BYE BYE.          (DEMO2 TYPES THIS)
*       >                 (DEMO2 EXITS TO HDOS)
ENTRY  LXI      H,DEMOA    EXECUTION STARTS HERE
       SCALL

*      LOOP ECHOING LINES

ECHO   SCALL  .SCIN
       JC     ECHO    NO CHARACTER YET
       CPI    '.'
       JNE    ECHO1   NOT PERIOD CHARACTER
       STA    ENDFLAG MAKE ENDFLAG NON-ZERO
                      (A '.', IN FACT)
ECHO1  SCALL  .SCOUT  TYPE CHARACTER BACK
       LDA    ENDFLAG
       ANA    A
       JZ     ECHO    STILL MORE TO GO

*      HAVE SEEN '.' WILL RETURN TO HDOS

       XRA    A
       SCALL  .EXIT   RETURN TO HDOS

DEMOA  DB     12Q,'HI,I'M DEMO2!',212Q
ENDFLAG DB    0       <>0 IF TO EXIT
       END    ENTRY
