        XTEXT   HDOS
        ORG     USERFWA

***     DEMO.ASM - HEATH HDOS ASSEMBLY LANGUAGE
*
*       DEMO IS A SHORT ANdir
SIMPLE PROGRAM USED
*       TO DEMONSTRATE THE HDOS ASSEMBLER AND
*       THE HDOS OPERATING SYSTEM
*
*       THIS PROGRAM SIMPLY PRINTS TWO CODED
*       LINES ON THE SYSTEM CONSOLE TERMINAL.

ENTRY   LXI      H,MESA  (HL)=ADDRESS OF 1ST MSG
        SCALL    .PRINT  PRINT FIRS MESSAGE
        LXI      H,MESB  (HL)=ADDRESS OF 2ND MSG
        SCALL    .PRINT  PRINT 2ND MESSAGE

*       SEND A BELL TO THE TERMINAL

        MVI      A,07Q   (A)=ASCII BELL
        SCALL    .SCOUT  RING TERMINAL'S BELL

*       RETURN CONTROL TO HDOS OPERATING SYSTEM

        XRA      A       EXIT TO OPERATING SYSTEM
        SCALL    .EXIT

*       MESSAGES FOR .PRINT SCAL'S

MESA    DB   12Q,'HI THERE, SPORTS FANS','!'+200Q
        LON  G LIST THE BYTES OF THE NEXT MESSAGE
MESB    DB   12Q,'YOUR SYSTEM WORKS FINE','!'+200Q

        END  ENTRY     START EXECUTING AT 'ENTRY' LABEL
